
INSERT INTO [CRMP1_ADSDT].[dbo].[WIN_PB_DEP_HISTORY] ([MNTH_ID],[ACN],[DEP_BAL] ,[CNT_PRD],[IRN] ,[CNT_ACCT])
SELECT MNTH_ID,DEP_ACN
, SUM(a.DEP_EODBAL) AS DEP_EODBAL
, COUNT(DISTINCT DEP_ZPROJCD) 
,AVG(a.ACN_IRN) AS IRN
,COUNT(DISTINCT ACN_CID) AS [CNT_ACCT]
FROM CRMP1_IMGDT.DBO.ODS_DEP_M_2021 A
WHERE A.ACN_ZSTATCD<>4 and mnth_id >=202108
GROUP BY MNTH_ID,DEP_ACN



SELECT DISTINCT ACN INTO #CIFDEP
FROM [CRMP1_ADSDT].[dbo].WIN_PB_PREPARE_DATA
WHERE MNTH_ID=202109

---  select TOP 100 * FROM [CRMP1_ADSDT].[dbo].[WIN_PB_DEP_HISTORY] 

select TOP 100 
 202109 AS MNTH_ID
 , A.ACN
, SUM(CASE WHEN MNTH_ID BETWEEN 202106 AND 202108 THEN DEP_BAL ELSE NULL END) AS BAL_SUM_3M
, SUM(CASE WHEN MNTH_ID BETWEEN 202103 AND 202108 THEN DEP_BAL ELSE NULL END) AS BAL_SUM_6M

, AVG(CASE WHEN MNTH_ID BETWEEN 202106 AND 202108 THEN DEP_BAL ELSE NULL END) AS DEP_AVG_3M
, AVG(CASE WHEN MNTH_ID BETWEEN 202103 AND 202108 THEN DEP_BAL ELSE NULL END) AS DEP_AVG_6M
 
, AVG(CASE WHEN MNTH_ID BETWEEN 202106 AND 202108 THEN IRN ELSE NULL END) AS IRN_AVG_3M
, AVG(CASE WHEN MNTH_ID BETWEEN 202103 AND 202108 THEN IRN ELSE NULL END) AS IRN_AVG_6M
 
, AVG(CASE WHEN MNTH_ID BETWEEN 202106 AND 202108 THEN CNT_PRD ELSE NULL END) AS CNT_PRD_AVG_3M
, AVG(CASE WHEN MNTH_ID BETWEEN 202103 AND 202108 THEN CNT_PRD ELSE NULL END) AS CNT_PRD_AVG_6M
INTO [CRMP1_ADSDT].[dbo].[WIN_PB_DEP_SUMMARY]
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_DEP_HISTORY]  A
INNER JOIN #CIFDEP B ON A.ACN=B.ACN