



INSERT INTO [CRMP1_ADSDT].[dbo].[WIN_PB_LN_SUBPLAN_HISTORY] (MNTH_ID,CID,ZSUBPLAN)
SELECT  MNTH_ID,CID,ZSUBPLAN
FROM CRMP1_IMGDT.dbo.ODS_LN_M_2020
GROUP BY MNTH_ID,CID,ZSUBPLAN

SELECT MNTH_ID,COUNT(*)
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_LN_SUBPLAN_HISTORY]
GROUP BY MNTH_ID
ORDER BY MNTH_ID