
SELECT DISTINCT CID INTO #CID
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA]
WHERE MNTH_ID=202109

/**************************************/
 
 select 
  A.CID

  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202107 AND 202109 THEN TJD ELSE NULL END) AS CNT_ALL_DATE_3M
  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202104 AND 202109 THEN TJD ELSE NULL END) AS CNT_ALL_DATE_6M
  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202101 AND 202109 THEN TJD ELSE NULL END) AS CNT_ALL_DATE_9M

  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202107 AND 202109 THEN TOT ELSE NULL END) AS AMT_ALL_DATE_3M
  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202104 AND 202109 THEN TOT ELSE NULL END) AS AMT_ALL_DATE_6M
  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202101 AND 202109 THEN TOT ELSE NULL END) AS AMT_ALL_DATE_9M

  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202107 AND 202109 AND ISNULL(PRIN,0)>0 THEN TJD ELSE NULL END) AS CNT_PRIN_DATE_3M
  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202104 AND 202109 AND ISNULL(PRIN,0)>0 THEN TJD ELSE NULL END) AS CNT_PRIN_DATE_6M
  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202101 AND 202109 AND ISNULL(PRIN,0)>0 THEN TJD ELSE NULL END) AS CNT_PRIN_DATE_9M

  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202107 AND 202109 AND ISNULL([INT],0)>0 THEN TJD ELSE NULL END) AS CNT_INT_DATE_3M
  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202104 AND 202109 AND ISNULL([INT],0)>0 THEN TJD ELSE NULL END) AS CNT_INT_DATE_6M
  ,COUNT(DISTINCT CASE WHEN MNTH_ID BETWEEN 202101 AND 202109 AND ISNULL([INT],0)>0 THEN TJD ELSE NULL END) AS CNT_INT_DATE_9M

  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202107 AND 202109 THEN PRIN ELSE NULL END) AS AMT_PRIN_DATE_3M
  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202104 AND 202109 THEN PRIN ELSE NULL END) AS AMT_PRIN_DATE_6M
  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202101 AND 202109 THEN PRIN ELSE NULL END) AS AMT_PRIN_DATE_9M

  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202107 AND 202109 THEN [INT] ELSE NULL END) AS AMT_INT_DATE_3M
  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202104 AND 202109 THEN [INT] ELSE NULL END) AS AMT_INT_DATE_6M
  ,SUM(DISTINCT CASE WHEN MNTH_ID BETWEEN 202101 AND 202109 THEN [INT] ELSE NULL END) AS AMT_INT_DATE_9M


 INTO CRMP1_ADSDT.DBO.WIN_TMP_PB_TXN_9M
 FROM [CRMP1_IMGDT].[dbo].[ODS_DTJ_M_2021] A  WITH (NOLOCK)
 INNER JOIN #CID B ON A.CID=B.CID 
 where 1=1 AND MNTH_ID BETWEEN 202101 AND 202109 
 AND CLS='L' AND GRP='COM' AND ITC1=1
 AND ETC  NOT IN ('CMAJID','CMPOVC') 
 GROUP BY A.CID 


 -- DROP TABLE CRMP1_ADSDT.DBO.WIN_TMP_PB_TXN_6M

INSERT INTO WIN_PB_TXN_HISTORY (
       MNTH_ID
      ,[CID]
      ,[CNT_ALL_DATE_3M]
      ,[CNT_ALL_DATE_6M]
      ,[AMT_ALL_DATE_3M]
      ,[AMT_ALL_DATE_6M]
      ,[CNT_PRIN_DATE_3M]
      ,[CNT_PRIN_DATE_6M]
      ,[CNT_INT_DATE_3M]
      ,[CNT_INT_DATE_6M]
      ,[AMT_PRIN_DATE_3M]
      ,[AMT_PRIN_DATE_6M]
      ,[AMT_INT_DATE_3M]
      ,[AMT_INT_DATE_6M]
	  )
 SELECT        
       202109 AS MNTH_ID
      ,[CID]
      ,[CNT_ALL_DATE_3M]
      ,[CNT_ALL_DATE_6M]
      ,[AMT_ALL_DATE_3M]
      ,[AMT_ALL_DATE_6M]
      ,[CNT_PRIN_DATE_3M]
      ,[CNT_PRIN_DATE_6M]
      ,[CNT_INT_DATE_3M]
      ,[CNT_INT_DATE_6M]
      ,[AMT_PRIN_DATE_3M]
      ,[AMT_PRIN_DATE_6M]
      ,[AMT_INT_DATE_3M]
      ,[AMT_INT_DATE_6M]
 FROM CRMP1_ADSDT.DBO.WIN_TMP_PB_TXN_6M



 SELECT TOP 100 * FROM CRMP1_ADSDT.DBO.WIN_TMP_PB_TXN_6M
 

 --  TRUNCATE TABLE CRMP1_ADSDT.DBO.WIN_PB_TXN_HISTORY