

/****** START  ******/

-- truncate table [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA]

INSERT INTO [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] (
 MNTH_ID
,CID
,ACN
,TYPE_COL
,[BRCD]
,[LOAN_AMT]
,[ACR]
,[DUPR]
,[DUIN]
,[LCHG]
,AGE_CID
,AGE_CID_REMAIN
)
SELECT    
 202109 AS [MNTH_ID]
,CID
,ACN
,[TYPE]
,[BRCD] 
,CASE WHEN BAL<>'' THEN CAST(BAL AS DECIMAL(18,2)) ELSE 0.00 END AS  BAL
,CASE WHEN [ACR]<>'' THEN CAST([ACR] AS DECIMAL(18,2)) ELSE 0.00 END AS  [ACR]
,CASE WHEN [DUPR]<>'' THEN CAST([DUPR] AS float) ELSE 0.00 END AS  [DUPR]
,CASE WHEN [DUIN]<>'' THEN CAST([DUIN] AS float) ELSE 0.00 END AS  [DUIN]
,CASE WHEN LCHG<>'' THEN CAST([LCHG] AS float) ELSE 0.00 END AS  [LCHG]

,DATEDIFF(MONTH,ODT,[MDT]) AS AGE_CID 
,DATEDIFF(MONTH,GETDATE(),[MDT]) AS AGE_CID_REMAIN 
FROM [CRMP1_BIDT].[dbo].CUSTOMER_INDICATOR_20210930
-- WHERE MNTH_ID=202109
WHERE [TYPE] IN ('7100','7200','7300','8100','8200')
 
 /******************************************/

 /*

 ALTER TABLE CRMP1_ADSDT.[dbo].[WIN_PB_PREPARE_DATA] ADD TYPE_COL INT
 ALTER TABLE CRMP1_ADSDT.[dbo].[WIN_PB_PREPARE_DATA] ADD ZKTBCCODE INT
 ALTER TABLE CRMP1_ADSDT.[dbo].[WIN_PB_PREPARE_DATA] ADD FLAG_PERSON INT

 SELECT TOP 1000 CREDIT_LIMIT,loan_amt,*
 FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
 INNER JOIN CRMP1_IMGDT.DBO.ODS_LN_M_2021 B ON A.CID=B.CID AND A.MNTH_ID=B.MNTH_ID
 WHERE A.MNTH_ID=202109
 
 SELECT TOP 1000 CREDIT_LIMIT,loan_amt,*
 FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
 where CREDIT_LIMIT=0

 
 SELECT  CCL,CRLMT,BAL,* FROM CRMP1_IMGDT.DBO.ODS_LN_M_2021
 WHERE MNTH_ID=202109 
 AND CID=800035919152

 SELECT *
 FROM [CRMP1_BIDT].[dbo].CUSTOMER_INDICATOR_20210930
 WHERE CID='800035919152'



 */
 
 --UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
 --SET TYPE_COL=B.[TYPE]
 --FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
 --INNER JOIN [CRMP1_BIDT].[dbo].CUSTOMER_INDICATOR_20210930 B ON A.CID=B.CID

 /******************* Update Loan info / multi column ***********************/
UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
 SET ACN=B.ACN
     ,CREDIT_LIMIT=CRLMT
	 ,LAST_PAYMENT_DATE_DAY=DATEDIFF(DAY,LPDT,GETDATE())
	 ,PCM=B.PCM
	 ,PMT=B.PMT
	 ,INT_RATE=IRN
	 ,PERIOD_BILL_M= DATEDIFF(MONTH,BLDT,BNDT) --- 
 FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
 INNER JOIN CRMP1_IMGDT.DBO.ODS_LN_M_2021 B ON A.CID=B.CID AND A.MNTH_ID=B.MNTH_ID
 WHERE A.MNTH_ID=202109



  UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
 SET PM_BAL_PERCENT= CASE WHEN CREDIT_LIMIT>LOAN_AMT THEN  CAST(ROUND(((LOAN_AMT)/CREDIT_LIMIT)*100,0) AS decimal(18,0)) ELSE 0 END 
 ,PER_GAP_UTL= CASE WHEN CREDIT_LIMIT>LOAN_AMT THEN  CAST(ROUND(((CREDIT_LIMIT-LOAN_AMT)/CREDIT_LIMIT)*100,0) AS decimal(18,0)) ELSE 0 END 
 where  MNTH_ID=202109 AND ISNULL(CREDIT_LIMIT,0)>0


 /********************/
 UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
 SET  INT_RATE=IRN
 FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
 INNER JOIN CRMP1_IMGDT.DBO.ODS_LN_M_2021 B ON A.CID=B.CID AND A.MNTH_ID=B.MNTH_ID
 WHERE A.MNTH_ID=202109

 
 ALTER TABLE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] ALTER COLUMN TERM_MNTH VARCHAR(30)

 UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
 SET  TERM_MNTH=RTRIM(TRM)
 FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
 INNER JOIN CRMP1_IMGDT.DBO.ODS_BAL_AGING_2021 B ON A.CID=B.CID AND A.MNTH_ID=B.MNTH_ID
 WHERE A.MNTH_ID=202109

 --alter table [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] ADD TERM_MNTH_NUM INT

 
  UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA]   
  SET TERM_MNTH_NUM=( CAST( REPLACE(TERM_MNTH,'Y','') AS INT)*12)
  WHERE TERM_MNTH LIKE '%Y%'
 
   UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA]  
  SET TERM_MNTH_NUM=( CAST( REPLACE(TERM_MNTH,'M','') AS INT)*1)
  WHERE TERM_MNTH LIKE '%M%'

  
   UPDATE CRMP1_ADSDT.DBO.[WIN_PB_PREPARE_DATA]  
  SET TERM_MNTH_NUM=( CAST( REPLACE(TERM_MNTH,'Q','') AS INT)*3)
  WHERE TERM_MNTH LIKE '%Q%' 

    
  UPDATE CRMP1_ADSDT.DBO.[WIN_PB_PREPARE_DATA]  
  SET TERM_MNTH_NUM=( CAST( REPLACE(TERM_MNTH,'D','') AS INT)/30)
  WHERE TERM_MNTH LIKE '%D%' 

  UPDATE CRMP1_ADSDT.DBO.[WIN_PB_PREPARE_DATA]  
  SET TERM_MNTH_NUM=( CAST( REPLACE(TERM_MNTH,'D','') AS INT)/30)
  WHERE TERM_MNTH LIKE '%D%' 
   
 
 --SELECT TOP 100 * FROM CRMP1_IMGDT.DBO.ODS_BAL_AGING_2021 WHERE MNTH_ID=202109
 

 /**********  CIF  **********/
 /* TYPE_COL=0 is Person */

UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
SET ZKTBCCODE=C.ZKTBCCODE
    ,FLAG_PERSON = CASE WHEN C.TYPE_COL=0 THEN 1 ELSE 0 END 
	,AGE = case WHEN DOB IS NOT NULL THEN DATEDIFF(YEAR,DOB,GETDATE()) ELSE NULL END 
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] D
INNER JOIN CRMP1_IMGDT.DBO.ODS_CIF C ON D.ACN=C.ACN


UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
SET  AGE_LNREG = case WHEN REGDATE IS NOT NULL THEN DATEDIFF(YEAR,REGDATE,GETDATE()) ELSE NULL END 
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] D
INNER JOIN CRMP1_IMGDT.DBO.ODS_CIFREG C ON D.ACN=C.ACN


SELECT B.ACN
,SUM(A.DEP_EODBAL) AS DEP_BAL
,COUNT(DISTINCT  ISNULL(DEP_TYPE,'')+'-'+ISNULL(DEP_ZPROJCD,'')) AS CNT_PRD
INTO #DEP_CIF
FROM  CRMP1_IMGDT.DBO.ODS_DEP_M_2021 A
INNER JOIN [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] B ON A.DEP_ACN=B.ACN AND A.MNTH_ID=B.MNTH_ID
WHERE A.MNTH_ID=202109
AND ACN_ZSTATCD<>4
GROUP BY B.ACN


UPDATE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
SET  DEP_BAL=C.DEP_BAL
, DEP_CNT_PRD=C.CNT_PRD
, DEP_CNT_ACCT = C.CNT_ACCT
, DEP_BAL_AVGBYACCT = C.DEP_BAL_AVGBYACCT
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] D
INNER JOIN #DEP_CIF C ON D.ACN=C.ACN


SELECT ACN
,COUNT(DISTINCT CID) AS LN_CNT_ACCT
,COUNT(DISTINCT ISNULL([TYPE],'')+''+ISNULL(ZMKTCD,'')) AS LN_CNT_PRD
INTO #LN_CNT_ACCT
FROM  [CRMP1_BIDT].[dbo].CUSTOMER_INDICATOR_20210930
WHERE 1=1
GROUP BY ACN

--ALTER TABLE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA]  ADD LN_CNT_ACCT INT 
--ALTER TABLE [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA]  ADD LN_CNT_PRD INT

UPDATE  [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
SET LN_CNT_ACCT=L.LN_CNT_ACCT
 , LN_CNT_PRD=L.LN_CNT_PRD
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
INNER JOIN #LN_CNT_ACCT L ON A.ACN=L.ACN


/******** Branch  ********/
UPDATE  [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] 
SET  SUB_REG_CD=B.SUB_REG_CD
FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] A
INNER JOIN CRMP1_DMDT.dbo.MAST_BRN_ALL B ON A.BRCD=B.BRN_CD

 /*
  UPDATE CRMP1_ADSDT.DBO.[WIN_PB_PREPARE_DATA] 
  SET DARCLS = B.DARCLS
  FROM CRMP1_ADSDT.DBO.[WIN_PB_PREPARE_DATA] A
  INNER JOIN [CRMP1_BIDT].[dbo].CUSTOMER_INDICATOR_20210930 B ON A.CID=B.CID
  where MNTH_ID=202109
  */

 /******** Define Target  ********/

  UPDATE CRMP1_ADSDT.DBO.[WIN_PB_PREPARE_DATA]  
  SET TARGET_NPL=CASE WHEN DARCLS IS NOT NULL THEN  CASE WHEN DARCLS>=3 THEN 1 ELSE 0 END  ELSE NULL END
  where MNTH_ID=202109


/** Data Used for Begin **/
/*

SELECT TOP (1000) [MNTH_ID]
      ,[CID]
      ,[TYPE_COL]
      ,[BRCD]
      ,[ACN]
      ,[CONDITION_SELECT]
      ,[MODEL_SELECTED]
      ,[TARGET_NPL]
      ,[ACR]
      ,[LOAN_AMT]
      ,[CREDIT_LIMIT]
      ,[INT_RATE]
      ,[DUIN]
      ,[DUPR]
      ,[LCHG]
      ,[AGE]
      ,[AGE_CID]
      ,[AGE_CID_REMAIN]
      ,[AGE_LNREG]
      ,[LAST_PAYMENT_DATE_DAY]
      ,[TERM_MNTH]
      ,[DEP_BAL]
      ,[DEP_CNT_PRD]

      ,[RANGE_ROUND_BILL_M]
      ,[PAYMENT_LN_PRIN_PERCENT]
      ,[PER_GAP_UTL]
      ,[PMT]
      ,[PM_BAL_PERCENT]
      ,[PCM]
      ,[PERIOD_BILL_M]
      ,[SUB_REG_CD]
      ,[ZKTBCCODE]
      ,[FLAG_PERSON]

	  ,LN_CNT_ACCT
	  ,LN_CNT_PRD 
  FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] WITH (NOLOCK)



  select top 100  *
    FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] WITH (NOLOCK)
	 


SELECT LPDT, *
FROM CRMP1_IMGDT.DBO.ODS_BAL_AGING_2021 WHERE MNTH_ID=202109 AND CID=500254036173


  */