 
  select P.[MNTH_ID]
      ,P.[CID]
      ,[TYPE_COL]
      ,[BRCD]
      ,P.[ACN]
      ,[CONDITION_SELECT]
      ,[MODEL_SELECTED]
      ,[TARGET_NPL]
      ,[ACR]
      ,[LOAN_AMT]
      ,[CREDIT_LIMIT]
      ,[INT_RATE]
      ,[DUIN]
      ,[DUPR]
      ,[LCHG]
      ,[AGE]
      ,[AGE_CID]
      ,[AGE_CID_REMAIN]
      ,[AGE_LNREG]
      ,[LAST_PAYMENT_DATE_DAY]
      ,[TERM_MNTH]
      ,[DEP_BAL]
      ,[DEP_CNT_PRD]
      ,[RANGE_ROUND_BILL_M]
      ,[PER_GAP_UTL]
      ,[PMT]
      ,[PM_BAL_PERCENT]
      ,[PCM]
      ,[PERIOD_BILL_M]
      ,[SUB_REG_CD]
      ,[ZKTBCCODE]
      ,[FLAG_PERSON]
      ,[DEP_BAL_AVGBYACCT]
      ,[DEP_CNT_ACCT]
      ,[LN_CNT_ACCT]
      ,[LN_CNT_PRD]
      ,[TERM_MNTH_NUM]
      
,[ACR_SUM_3M]
,[ACR_SUM_6M]
,[ACR_AVG_3M]
,[ACR_AVG_6M]
,L.[BAL_SUM_3M] AS LN_BAL_SUM3M
,L.[BAL_SUM_6M] AS LN_BAL_SUM6M
,[BAL_AVG_3M] AS [LN_BAL_AVG_3M]
,[BAL_AVG_6M] AS [LN_BAL_AVG_6M]
,[CRLMT_SUM_3M]
,[CRLMT_SUM_6M]
,[CRLMT_AVG_3M]
,[CRLMT_AVG_6M]
,[INT_RATE_SUM_3M]
,[INT_RATE_SUM_6M]
,[INT_RATE_AVG_3M]
,[INT_RATE_AVG_6M]
,[DUIN_SUM_3M]
,[DUIN_SUM_6M]
,[DUIN_AVG_3M]
,[DUIN_AVG_6M]
,[DUPR_SUM_3M]
,[DUPR_SUM_6M]
,[DUPR_AVG_3M]
,[DUPR_AVG_6M]
,[CNT_NPL_3M] AS [LN_CNT_NPL_3M]
,[CNT_NPL_6M] AS [LN_CNT_NPL_6M]

      ,T.[CNT_ALL_DATE_6M] AS [TXN_CNT_ALL_DATE_6M]
      ,T.[AMT_ALL_DATE_6M] AS [TXN_AMT_ALL_DATE_6M]
      ,T.[CNT_PRIN_DATE_6M]  AS [TXN_CNT_PRIN_DATE_6M]
      ,T.[CNT_INT_DATE_6M]  AS [TXN_CNT_INT_DATE_6M]
      ,T.[AMT_PRIN_DATE_6M]  AS [TXN_AMT_PRIN_DATE_6M]
      ,T.[AMT_INT_DATE_6M] AS [TXN_AMT_INT_DATE_6M]

	  ,D.[BAL_SUM_3M] AS [DEP_SUM_3M]
      ,D.[BAL_SUM_6M] AS [DEP_SUM_6M]
      ,[DEP_AVG_3M] 
      ,[DEP_AVG_6M] 
      ,[IRN_AVG_3M] AS [DEP_IRN_AVG_3M]
      ,[IRN_AVG_6M] AS  [DEP_IRN_AVG_6M]
      ,[CNT_PRD_AVG_3M] AS [DEP_CNT_PRD_AVG_3M]
      ,[CNT_PRD_AVG_6M] AS [DEP_CNT_PRD_AVG_6M]

	  ,[DARCLS_CNT] AS [DARCLS_CNT_4Y]
      ,[DARCLS_AVG] AS [DARCLS_AVG_4Y]
 
      ,[DARCLS_NORMAL_CNT] AS [DARCLS_NORMAL_CNT_4Y]
      ,[DARCLS_NPL_CNT] AS [DARCLS_NPL_CNT_4Y]
      ,[NORMAL_PERS] AS [NORMAL_PERS_4Y]
      ,[NPL_PERS] AS [NPL_PERS_4Y]

	  , [CNT_ZSUBPLAN] /** 2Y **/

	  , cast([INC_TOTALINCOME] as float) as [INC_TOTALINCOME]
	  , cast([EXP_TOTALCOST] as float) as [EXP_TOTALCOST]
	   
	  , CASE WHEN ISNULL([INC_TOTALINCOME],0)>0 THEN  (CAST([EXP_TOTALCOST] AS FLOAT)/ CAST([INC_TOTALINCOME] AS float))*100 ELSE  0 END  AS DSR

	  INTO [CRMP1_ADSDT].[dbo].WIN_PB_DATA_IMPORT_MODEL
  FROM [CRMP1_ADSDT].[dbo].[WIN_PB_PREPARE_DATA] P
  LEFT JOIN [CRMP1_ADSDT].[dbo].[WIN_PB_LN_SUMMARY] L ON P.CID=L.CID AND P.MNTH_ID=L.MNTH_ID
  LEFT JOIN [CRMP1_ADSDT].[dbo].[WIN_PB_DEP_SUMMARY] D ON P.[ACN]=D.[ACN] AND P.MNTH_ID=D.MNTH_ID
  LEFT JOIN  [CRMP1_ADSDT].[dbo].[WIN_PB_TXN_HISTORY] T  ON P.CID=T.CID AND P.MNTH_ID=T.MNTH_ID
  LEFT JOIN  [CRMP1_ADSDT].[dbo].[WIN_PB_DARCLS_SUMMARY] N  ON P.CID=N.CID AND P.MNTH_ID=N.MNTH_ID
  LEFT JOIN  [CRMP1_ADSDT].[dbo].[WIN_PB_LN_SUBPLAN_SUMMARY] S  ON P.CID=S.CID --AND P.MNTH_ID=S.MNTH_ID
  LEFT JOIN  [CRMP1_ADSDT].[dbo].[WIN_PEOPLE_HEAD_¨»°] H  ON P.ACN=H.CIF_NUM 
  WHERE 1=1

  -- DROP TABLE [CRMP1_ADSDT].[dbo].WIN_PB_DATA_IMPORT_MODEL
  
  /************ Checking Row count compare with Table Green Yellow Red **************/
  SELECT COUNT(*) 
  FROM [CRMP1_ADSDT].[dbo].WIN_PB_DATA_IMPORT_MODEL 
  --- 9,982,130

  SELECT  COUNT(*) 
  FROM [CRMP1_BIDT].[dbo].CUSTOMER_INDICATOR_20210930
  WHERE [TYPE] IN ('7100','7200','7300','8100','8200')
  ---- 9982130

  /***************************** Selection  ********************************************/
  SELECT TOP 100 *
  FROM [CRMP1_ADSDT].[dbo].WIN_PB_DATA_IMPORT_MODEL 

  UPDATE [CRMP1_ADSDT].[dbo].WIN_PB_DATA_IMPORT_MODEL SET CONDITION_SELECT=1 WHERE [TYPE_COL]=8200

  /***************************** Sampling  ********************************************/

  SELECT  TARGET_NPL,count(*)
  FROM CRMP1_ADSDT.DBO.WIN_PB_DATA_IMPORT_MODEL 
  WHERE CONDITION_SELECT=1 
  group by TARGET_NPL

  -- 4,432,563
  /********************************/

  SELECT  CID INTO  #CID_SEL
  FROM CRMP1_ADSDT.DBO.WIN_PB_DATA_IMPORT_MODEL 
  WHERE CONDITION_SELECT=1 AND TARGET_NPL=0 --AND DEP_BAL IS NOT NULL

  /*************** Create Table sampling  *****************/

  SELECT * INTO #CID_SEL_SAMPLING  FROM #CID_SEL TABLESAMPLE (1000000 ROWS)

  SELECT COUNT(*) FROM #CID_SEL_SAMPLING

  
  /*************** Select Data for import model  *****************/

  UPDATE CRMP1_ADSDT.DBO.WIN_PB_DATA_IMPORT_MODEL  SET MODEL_SELECTED=0

  UPDATE CRMP1_ADSDT.DBO.WIN_PB_DATA_IMPORT_MODEL  
  SET MODEL_SELECTED=1
  WHERE CONDITION_SELECT=1 AND  TARGET_NPL=1 
  
  UPDATE CRMP1_ADSDT.DBO.WIN_PB_DATA_IMPORT_MODEL  
  SET MODEL_SELECTED=1
  WHERE CONDITION_SELECT=1 AND  TARGET_NPL=0 AND CID IN (SELECT CID FROM #CID_SEL_SAMPLING)
  
  SELECT TARGET_NPL,COUNT(*)
  FROM CRMP1_ADSDT.DBO.WIN_PB_DATA_IMPORT_MODEL
  WHERE MODEL_SELECTED=1
  GROUP BY TARGET_NPL

