/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [YYYY]
      ,[VILLID]
      ,[PP]
      ,[AA]
      ,[TT]
      ,[MM]
      ,[PP_NAME]
      ,[AA_NAME]
      ,[TT_NAME]
      ,[MM_NAME]
      ,[REGION]
      ,[ISSURVEYED]
      ,[HOUSEID]
      ,[HEADID]
      ,[HEADAGE]
      ,[HEADAGEMONTH]
      ,[HEADSEX]
      ,[HHNUMBER]
      ,[NUMMEMBER]
      ,[HAPPINESS]
      ,[EXP_COST]
      ,[EXP_NEEDED]
      ,[EXP_UNNEEDED]
      ,[EXP_DEBT]
      ,[EXP_TOTALCOST]
      ,[EXP_AVGCOST]
      ,[INC_MAIN]
      ,[INC_ALTERNATE]
      ,[INC_OTHER]
      ,[INC_SELF]
      ,[INC_TOTALINCOME]
      ,[INC_AVGINCOME]
  FROM [CRMP1_ADSDT].[dbo].[WIN_PEOPLE_HEAD_จปฐ]
  WHERE HEADID='3461300488329'

  select 
  HEADID,ACN INTO #TEMP_HEAD_CIF
  FROM [CRMP1_ADSDT].[dbo].[WIN_PEOPLE_HEAD_จปฐ] A
  INNER JOIN CRMP1_IMGDT.DBO.ODS_CIF B ON A.HEADID=B.ZCIZID


  SELECT COUNT(*) FROM [CRMP1_ADSDT].[dbo].[WIN_PEOPLE_HEAD_จปฐ] 

  SELECT TOP 100 * FROM #TEMP_HEAD_CIF

  -- 11,422,526
  -- 8,502,091
  

  SELECT COUNT(*) AS CNT
  ,COUNT(DISTINCT HEADID) AS CNT_PUBLICID 
  ,COUNT(DISTINCT ACN) AS CNT_CIF 
  FROM #TEMP_HEAD_CIF


  SELECT ACN,A.HEADID
        ,EXP_TOTALCOST,INC_TOTALINCOME
  INTO CRMP1_ADSDT.DBO.WIN_MAPPING_จปฐ
  FROM #TEMP_HEAD_CIF A
  INNER JOIN [CRMP1_ADSDT].[dbo].[WIN_PEOPLE_HEAD_จปฐ] B ON A.HEADID=B.HEADID
  WHERE 1=1

  -- DROP TABLE CRMP1_ADSDT.DBO.WIN_MAPPING_จปฐ
